### ISSUE TITLE
Lemma list errors

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/tagger-part-of-speech#2]
in 1 Cor 1 ϣⲟⲟⲡ is lemmatized as  ϣⲟⲟⲡ not ϣⲱⲡⲉ.  Check lemma list.

**Comment by amir-zeldes** [comment]
Updated in lemma list and pipeline. New tagger model awaiting release (incl. behavior of mpr)

**Comment by amir-zeldes** [comment]
Tagger updated to match.
