### ISSUE TITLE
compound verbs with imperative form

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/tagger-part-of-speech#4]
If you have a compound verb with an imperative form as part of the verb and a regular form for the other part, how is it tagged?  VIMP or V?  (Contextually the meaning is imperative, but I know we only tag VIMP if the form has changed.)  Posting here since it might be something to address in guidelines.

ⲡϫⲟⲉⲓⲥ ϩⲛⲧⲉⲓⲟⲩⲛⲟⲩ ⲙⲁⲧⲟⲩϫⲟⲓ ⲉⲧⲃⲉ ⲛⲉϣⲗⲏⲗ ⲙⲡⲁⲉⲓⲱⲧ

ⲙⲁⲧⲟⲩϫⲟⲓ is ⲙⲁ-ⲧⲟⲩϫⲟ|ⲓ where ⲙⲁ is the imperative of ϯ (then compounded with ⲧⲟⲩϫⲟ to form a verb that takes a personal pronoun object).

**Comment by amir-zeldes** [comment]
It's VIMP, since it has a special imperative form. Just like ma! is VIMP of the lemma ti, so do the compound versions of ti-X (V) have their own imperatives, ma-X (VIMP). I'll update the guidelines.

**Comment by amir-zeldes** [comment]
Actually scratch that, ma-toujo=i is not a compound: the pronoun =i makes it definite (like an article), so it doesn't fall under compounding guidelines. The verb is plain old "ma", which is also VIMP, but "toujo" is N (and i is PPERO). 

A better example of the guideline above is: arihmhal (VIMP, imperative of compound rhmhal). I've updated the guidelines with the latter example.
